import type { Analysis } from './types'

export const demoAnalysis: Analysis = {
  id: 'anl_demo_7J3K',
  claimId: 'CLM-20481',
  status: 'COMPLETED_WITH_WARNINGS',
  analysisVersion: 1,
  reviewPriority: 'HIGH',
  extractionQuality: 94,
  coverage: 75,
  scenario: 'Inconsistent packet',
  createdAt: '2026-09-17T06:42:00Z',
  claimedAmountPaise: 24850000,
  documents: [
    {
      id: 'doc_bill_v1',
      name: 'CityCare_itemized_bill.pdf',
      type: 'BILL',
      version: 1,
      pages: 3,
      extractionQuality: 96,
      status: 'READY',
    },
    {
      id: 'doc_discharge_v1',
      name: 'discharge_summary.pdf',
      type: 'DISCHARGE_SUMMARY',
      version: 1,
      pages: 2,
      extractionQuality: 94,
      status: 'READY',
    },
    {
      id: 'doc_report_v1',
      name: 'operative_report.pdf',
      type: 'SUPPORTING_REPORT',
      version: 1,
      pages: 2,
      extractionQuality: 91,
      status: 'READY',
    },
  ],
  findings: [
    {
      id: 'f_total',
      checkId: 'bill.total_reconciliation',
      title: 'Invoice total does not reconcile',
      status: 'FINDING',
      priority: 'HIGH',
      reviewerAction: 'OPEN',
      summary:
        'Line items sum to ₹241,500.00, which is ₹7,000.00 below the stated invoice total of ₹248,500.00. Tolerance: ₹1.00.',
      evidence: [
        {
          evidenceId: 'ev_total',
          documentId: 'doc_bill_v1',
          documentName: 'CityCare_itemized_bill.pdf',
          page: 3,
          blockIds: ['blk-71'],
          geometry: { left: 0.61, top: 0.71, width: 0.28, height: 0.035 },
          confidence: 98.4,
          excerpt: 'Invoice Total ₹248,500.00',
        },
        {
          evidenceId: 'ev_lines',
          documentId: 'doc_bill_v1',
          documentName: 'CityCare_itemized_bill.pdf',
          page: 2,
          blockIds: ['blk-34', 'blk-41', 'blk-49', 'blk-52'],
          geometry: { left: 0.1, top: 0.28, width: 0.8, height: 0.31 },
          confidence: 96.8,
          excerpt: 'Room ₹45,000 · Surgery ₹88,000 · Implant ₹72,000 · Pharmacy ₹36,500',
        },
      ],
    },
    {
      id: 'f_timeline',
      checkId: 'packet.timeline',
      title: 'Procedure date precedes admission',
      status: 'FINDING',
      priority: 'HIGH',
      reviewerAction: 'OPEN',
      summary:
        'The operative report lists 05 Sep 2026, four days before admission on 09 Sep 2026. This exceeds the configured one-day allowance.',
      evidence: [
        {
          evidenceId: 'ev_procedure',
          documentId: 'doc_report_v1',
          documentName: 'operative_report.pdf',
          page: 1,
          blockIds: ['blk-8'],
          geometry: { left: 0.12, top: 0.24, width: 0.41, height: 0.03 },
          confidence: 93.1,
          excerpt: 'Procedure date: 05/09/2026',
        },
        {
          evidenceId: 'ev_admission',
          documentId: 'doc_discharge_v1',
          documentName: 'discharge_summary.pdf',
          page: 1,
          blockIds: ['blk-12'],
          geometry: { left: 0.12, top: 0.31, width: 0.39, height: 0.03 },
          confidence: 97.6,
          excerpt: 'Admission date: 09/09/2026',
        },
      ],
    },
    {
      id: 'f_identity',
      checkId: 'packet.patient_identity',
      title: 'Patient identifiers align',
      status: 'PASS',
      priority: 'LOW',
      reviewerAction: 'OPEN',
      summary:
        'The masked member ID agrees across the bill, discharge summary, and operative report.',
      evidence: [
        {
          evidenceId: 'ev_patient',
          documentId: 'doc_discharge_v1',
          documentName: 'discharge_summary.pdf',
          page: 1,
          blockIds: ['blk-4'],
          geometry: { left: 0.11, top: 0.16, width: 0.43, height: 0.04 },
          confidence: 99.0,
          excerpt: 'Patient: Asha Mehra · Member: ****4821',
        },
        {
          evidenceId: 'ev_patient_bill',
          documentId: 'doc_bill_v1',
          documentName: 'CityCare_itemized_bill.pdf',
          page: 1,
          blockIds: ['blk-3'],
          geometry: { left: 0.11, top: 0.16, width: 0.43, height: 0.04 },
          confidence: 98.0,
          excerpt: 'Member: ****4821',
        },
        {
          evidenceId: 'ev_patient_report',
          documentId: 'doc_report_v1',
          documentName: 'operative_report.pdf',
          page: 1,
          blockIds: ['blk-2'],
          geometry: { left: 0.11, top: 0.16, width: 0.43, height: 0.04 },
          confidence: 96.0,
          excerpt: 'Member: ****4821',
        },
      ],
    },
    {
      id: 'f_support',
      checkId: 'packet.supporting_evidence',
      title: 'Implant invoice is missing',
      status: 'INSUFFICIENT_EVIDENCE',
      priority: 'MEDIUM',
      reviewerAction: 'OPEN',
      summary:
        'The bill contains an implant charge, but this packet does not include the referenced implant invoice. This does not mean the implant was not used.',
      requestedEvidence: 'Request the implant invoice or implant sticker record.',
      evidence: [
        {
          evidenceId: 'ev_implant',
          documentId: 'doc_bill_v1',
          documentName: 'CityCare_itemized_bill.pdf',
          page: 2,
          blockIds: ['blk-49'],
          geometry: { left: 0.1, top: 0.59, width: 0.78, height: 0.035 },
          confidence: 94.5,
          excerpt: 'Orthopaedic implant ₹72,000.00',
        },
      ],
    },
  ],
}
